export default {
  batchImageGuide: {
    title: '圖片批次生成', description: '一次提交多條提示詞，任務完成後可統一下載圖片結果',
    ui: {
      searchPlaceholder: '搜尋任務名稱', reset: '重設', refresh: '重新整理', guide: '使用說明', create: '建立批次任務', selectedJobs: '已選擇 {count} 個任務', downloadSelected: '下載所選項目', deleteRecord: '刪除記錄',
      collapseChildren: '收起子任務', expandChildren: '展開 {count} 個子任務', childJobs: '{count} 個子任務', childJob: '子任務', notRecorded: '未記錄', totalCount: '共 {count} 個', notDownloaded: '未下載', viewDetails: '查看詳情', view: '查看', downloadZip: '下載 ZIP', download: '下載', moreActions: '更多操作', more: '更多', emptyTitle: '暫無批次任務', emptyHint: '請從右上角建立批次任務。',
      page: '第 {page} 頁', pageItems: '本頁 {count} 個', perPage: '每頁', previous: '上一頁', next: '下一頁', retryFailed: '重試失敗項目', fullPrompt: '完整 Prompt', copy: '複製', copiedPrompt: '已複製 Prompt', detailsTitle: '任務詳情', status: '狀態', summaryResult: '彙總結果', result: '結果', cost: '費用', downloadStatus: '下載狀態', details: '明細', customId: 'Custom ID', prompt: 'Prompt', preview: '預覽',
      zoomPreview: '放大壓縮預覽 {id}', reloadPreview: '重新載入壓縮預覽', loadPreview: '載入壓縮預覽', unavailablePreview: '無法預覽', noImage: '沒有圖片', loadingDetails: '正在載入明細...', noDetails: '暫無明細', pendingDetailHint: '排隊或生成中的任務會先顯示已提交的 Prompt，整理結果後會更新圖片狀態。', cancelJob: '取消任務', imagePreview: '圖片預覽', previewHint: '目前顯示的是瀏覽器本機緩存的壓縮縮圖；如要查看原圖，請下載 ZIP。',
      createTitle: '建立批次任務', taskName: '任務名稱', taskNamePlaceholder: '留空則預設使用目前時間', loadingKeys: '正在載入 API Key...', selectGeminiKey: '請選擇 Gemini API Key', noKeys: '目前沒有可用於批次生圖的 Gemini API Key。請先建立並綁定已啟用批次生圖的 Gemini 分組。', model: '模型', imageSize: '圖片尺寸', imageSizeHint: '目前批次任務固定以 1K 圖片提交。', outputFormat: '輸出格式', estimated: '預計生成', estimateFormat: '{images} 張 / {prompts} 條', addedPrompts: '已加入 {count} 條', promptPlaceholder: '貼上 Prompt，然後加入下方清單', customIdPlaceholder: 'Custom ID（可選）', outputCount: '每條生成張數', imageCount: '{count} 張', referenceImage: '參考圖', add: '加入', removeReferenceImage: '移除參考圖',
      referenceLimit: '每條最多 {perItem} 張，整組最多 {perJob} 張；目前模型每條最多 {references} 張參考圖，參考圖會按生成張數重複消耗輸入 Token。', referenceCount: '{count} 張參考圖', delete: '刪除', emptyPrompts: '尚未加入 Prompt。', cancelWarning: '取消任務會向上游提出取消；已被系統索引為成功的圖片仍會按成功項目收費，其餘凍結金額會釋放。', submittingHint: '正在建立上游批次任務，通常需要數秒，請勿重複提交。', cancel: '取消', submitting: '提交中...', submit: '提交任務',
      guideTitle: '批次生圖使用說明', guideHowTo: '如何使用此畫面', guideStep1: '1. 選擇已啟用批次生圖的 Gemini API Key；模型清單只會顯示該 Key 所屬分組可用的模型。', guideStep2: '2. 任務名稱可留空；Prompt 需逐條加入，每條可附上參考圖並設定生成張數。', guideStep3: '3. 提交後任務會先排隊；圖片預覽只會在需要時載入。', guideStep4: '4. 完成後可下載 ZIP；部分失敗時可只重試失敗項目，費用按成功輸出圖片數計算。', guideSkillTitle: 'Codex Skill 說明', guideSkillDescription: '告訴 Codex 如何整理 Prompt、提交任務、查詢狀態及下載結果。', close: '關閉', copyInstructions: '複製說明',
      columns: { task: '任務名稱', model: '模型', apiKey: '提交金鑰', status: '狀態', result: '結果', cost: '費用', downloaded: '下載狀態', actions: '操作' }, filters: { allStatuses: '全部狀態', allDownloads: '全部下載狀態', downloaded: '已下載', notDownloaded: '未下載', allApiKeys: '全部 API Key' },
      sourceMain: '主任務：{name}', sourceChild: '子任務：{name}', retryTaskName: '{name} 重試失敗項目', hold: '已凍結 {amount}', referenceUnsupported: '目前模型不支援參考圖。', referencePerItem: '目前模型每條最多 {count} 張參考圖。', referenceIgnored: '目前模型每條最多 {count} 張參考圖，超出部分已略過。', referenceFormat: '參考圖只支援 PNG、JPEG 或 WebP。', referenceTooLarge: '{name} 超過 10MB，已略過。', errorCode: '錯誤碼：{code}', requestId: '請求 ID：{id}', httpStatus: 'HTTP 狀態：{status}', errorDetail: '錯誤資訊'
    },
    status: { queued: '排隊中', running: '生成中', indexing: '整理結果', processing_results: '整理結果', settling: '結算中', completed: '已完成', failed: '失敗', cancelled: '已取消', output_deleted: '結果已刪除', partial: '部分成功', allFailed: '全部失敗', pending: '排隊中', succeeded: '成功', success: '成功', recovered: '已補回成功' },
    results: { recovered: '舊有失敗項目已由重試子任務補回成功', previewReady: '圖片已生成，可點擊預覽', downloadReady: '圖片已生成，可下載', noImage: '未生成可用圖片', cancelled: '任務已取消', waiting: '等待生成結果', emptyOutput: '上游已傳回結果，但此項目沒有圖片內容，可能是單項生成失敗或遭安全政策攔截。', providerFailed: '上游傳回的此項結果沒有可用圖片。' },
    messages: {
      loadKeysFailed: '載入 API Key 失敗', loadModelsFailed: '載入可用模型失敗', loadJobsFailed: '載入批次任務失敗', selectApiKey: '請選擇可用的 Gemini API Key', noModelsForKey: '目前金鑰沒有可用的批次生圖模型', selectModel: '請選擇模型', promptRequired: '請至少填寫一條 Prompt', submitted: '批次任務已提交', submitFailed: '提交失敗', refreshFailed: '重新整理失敗', cancelConfirm: '取消會向上游提出取消；成功圖片仍會結算，其餘凍結金額會釋放。確定取消嗎？', cancelled: '已提出取消任務', cancelFailed: '取消失敗', batchDownloadStarted: '已開始下載所選任務', downloadFailed: '下載失敗', retrySubmitted: '已提交失敗項目重試任務', retryFailed: '重試失敗項目失敗', retryMissingPrompts: '此任務沒有儲存失敗項目的 Prompt，無法自動重試。', deleteConfirm: '刪除後任務會從清單隱藏，但帳務記錄仍會保留。確定刪除嗎？', deleteSelectedConfirm: '刪除後所選任務會從清單隱藏，但帳務記錄仍會保留。確定刪除嗎？', deleted: '任務記錄已刪除', deleteFailed: '刪除任務記錄失敗', loadItemsFailed: '載入明細失敗', loadPreviewFailed: '載入圖片預覽失敗', copiedInstruction: '已複製批次生圖說明', loadingModels: '正在載入可用模型...', noModels: '沒有可用模型', noModelsHint: '目前金鑰所屬分組尚未設定批次生圖模型。', noCompatibleAccount: '目前金鑰所屬分組沒有可用的批次生圖上游帳號。', unsupportedProvider: '此任務的批次生圖渠道目前不可用。', providerSubmitFailed: '上游批次生圖任務提交失敗。', vertexGcsBucketMissing: 'Vertex 批次生圖缺少託管 GCS 儲存貯體設定。', queueFailed: '任務佇列暫時不可用。', billingHoldFailed: '費用凍結失敗，任務未能提交。', groupDisabled: '目前金鑰所屬分組尚未啟用批次生圖。', pricingMissing: '所選模型尚未設定批次生圖價格。', insufficientBalance: '餘額不足，無法凍結預計費用。', invalidModel: '請選擇目前金鑰可用的批次生圖模型。', invalidItems: 'Prompt 清單格式不正確。', duplicateCustomId: 'Custom ID 不可重複。', promptTooLong: '單條 Prompt 過長。', invalidReferenceImage: '參考圖格式不正確。', tooManyReferenceImages: '參考圖數量超過限制。', referenceImagesTooLarge: '參考圖總容量過大。', tooManyOutputImages: '預計生成張數超過限制。', idempotencyConflict: '本次提交與先前的請求識別碼衝突。', notReady: '任務尚未完成。', outputDeleted: '任務結果檔案已被清理。', resultMissing: '結果檔案不可用。', itemFailed: '此明細沒有成功圖片。', itemImageIndexOutOfRange: '此明細沒有可預覽圖片。', downloadLimited: '目前下載請求過多，請稍後再試。', downloadTooLarge: 'ZIP 超過單次下載限制。', deleteNotReady: '任務結束後才能刪除記錄。', disabled: '批次生圖功能目前未啟用。', authRequired: '目前 API Key 不可用或已失效。', adminReference: '請將錯誤碼和請求 ID 傳給管理員排查。', errorReference: '錯誤資訊'
    },
    agentInstruction: '使用 {endpoint} 的 Sub2API 批次生圖 API。從對話中整理 Prompt 和任務資料，選擇可用的 Gemini 或 Vertex 批次生圖模型，保持 Custom ID 穩定，預計輸出超過 200 張時拆分任務。切勿洩露 API Key 或參考圖 Base64。提交後儲存不含憑證的本機恢復記錄，低頻查詢狀態，只下載成功結果，並且只重試失敗項目。'
  }
}
